name: Deploy to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to Amazon ECR
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            473106654049.dkr.ecr.ap-southeast-2.amazonaws.com/a4medicine-frontend:${{ github.sha }}
            473106654049.dkr.ecr.ap-southeast-2.amazonaws.com/a4medicine-frontend:latest

      - name: Update Docker image on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            docker stop frontend
            docker rm frontend
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 473106654049.dkr.ecr.ap-southeast-2.amazonaws.com
            docker pull 473106654049.dkr.ecr.ap-southeast-2.amazonaws.com/a4medicine-frontend:${{ github.sha }}
            docker run -d --hostname frontend --name frontend --network a4medicine-frontend 473106654049.dkr.ecr.ap-southeast-2.amazonaws.com/a4medicine-frontend:${{ github.sha }}
